#
###################################
# Site wide configuration
####################################
#
title: fylwen
email: fylwen@iis.u-tokyo.ac.jp
description: 
url: https://fylwen.github.io # the base hostname & protocol for your site
keywords: ["computer vision", "robotics", "human computer interaction"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Asia/Tokyo
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Wen, Yilin Frances
  avatar: me.jpg
  job: #"Research Scientist"
  bio: #"Research Scientist at Niantic, Inc."
  email: fylwen@iis.u-tokyo.ac.jp
  disqus-shortname: 
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics: #UA-47703339-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: fylwen #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: fylwen10 #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  telegram: #username
  scholar: bH6lBeMAAAAJ
